version: '3.8'

services:
    php:
        container_name: orders_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./Project/:/app/
        network_mode: service:nginx # to allow connection to fastcgi://127.0.0.1:9000 upstream
    
    nginx:
        container_name: orders_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./Project/:/app/
        ports:
            - ${NGINX_PORT}:80
    
    firebird:
        container_name: orders_firebird
        build:
            context: .
            dockerfile: docker/firebird/Dockerfile
        environment:
            ISC_USER: sysdba
            ISC_PASSWORD: masterkey
            FIREBIRD_USER: sysdba
            FIREBIRD_PASSWORD: masterkey
            FIREBIRD_DATABASE: ORDER.fdb
        ports:
            - "3050:3050"
        volumes:
            # Optionally, you can mount a local directory to store the database files.
            # Replace "/path/to/your/local/directory" with your desired local directory.
            - "orders_firebird_volume:/firebird"
            - "./db:/firebird/data"
            - "./db_restore:/firebird/restore"

volumes:
    orders_firebird_volume: {}
