services:
    php:
        container_name: orders_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./docker/php/httpd.conf:/opt/docker/etc/httpd/conf.d/httpd.conf
            - ./docker/php/php.ini:/opt/docker/etc/php/php.ini
            - ./Project/:/app/
        links:
            - firebird
        ports:
            - "8080:8080"
    
    firebird:
        container_name: orders_firebird
        build:
            context: .
            dockerfile: docker/firebird/Dockerfile
        environment:
            ISC_USER: sysdba
            ISC_PASSWORD: masterkey
            FIREBIRD_USER: sysdba
            FIREBIRD_PASSWORD: masterkey
            FIREBIRD_DATABASE: ORDER.fdb
        ports:
            - "3050:3050"
        volumes:
            # Optionally, you can mount a local directory to store the database files.
            # Replace "/path/to/your/local/directory" with your desired local directory.
            - "orders_firebird_volume:/firebird"
            - "./db:/firebird/data"
            - "./db_restore:/firebird/restore"

volumes:
    orders_firebird_volume: {}
