version: '3.8'

services:
    php:
        container_name: orders_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        user: "1000:1000"
        volumes:
            - ./Project/:/app/
        network_mode: service:nginx # to allow connection to fastcgi://127.0.0.1:9000 upstream
    
    nginx:
        container_name: orders_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./Project/:/app/
        ports:
            - ${NGINX_PORT}:80
    
    phpmyadmin:
        container_name: orders_pma
        image: phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - ${PHPMYADMIN_PORT}:80
        restart: always
    
    db:
        container_name: orders_db
        image: mysql:8.0.33
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "orders_db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306

volumes:
    orders_db: {}
